# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciaTransp', '0003_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=8, verbose_name='Placa '),
        ),
    ]
