# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciaTransp', '0004_auto_20171204_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnh', models.CharField(max_length=50, verbose_name='CNH ')),
                ('categoria', models.CharField(max_length=10, verbose_name='Categoria ')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciaTransp.Funcionario')),
            ],
        ),
    ]
