# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciaTransp', '0005_motorista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome ')),
                ('setor', models.CharField(max_length=100, verbose_name='Setor ')),
            ],
        ),
    ]
