# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciaTransp', '0006_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gerenciaTransp.Departamento'),
            preserve_default=False,
        ),
    ]
