# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciaTransp', '0007_funcionario_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataH_ida', models.DateTimeField(blank=True, null=True)),
                ('origem', models.CharField(max_length=100, verbose_name='Origem ')),
                ('destino', models.CharField(max_length=100, verbose_name='Destino ')),
                ('dataH_volta', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=100, verbose_name='Motivo ')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciaTransp.Departamento')),
                ('funcionarios', models.ManyToManyField(max_length=100, to='gerenciaTransp.Funcionario')),
            ],
        ),
    ]
